spring:
  application:
    name: fiap-hackathon-pessoas
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/fiap

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
