spring:
  application:
    name: fiap-hackathon-pessoas
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_PROVIDER_ISSUER:http://dockerhost:7777/auth/realms/vodafone}

aws:
  region: us-east-1

management:
  health:
    probes:
      enabled: true
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
